// Glossary terms database with definitions
export const GLOSSARY_TERMS = {
  // Technology
  "artificial intelligence": "Machine learning systems that can learn and make decisions from data",
  "machine learning": "Computer systems that improve through experience without explicit programming",
  "algorithm": "Step-by-step procedure for solving a problem or accomplishing a task",
  "data": "Information or facts collected for analysis and reference",
  "encryption": "Process of converting information into code to prevent unauthorized access",
  "api": "Application Programming Interface - a set of tools for building software applications",
  "database": "Organized collection of structured data stored in a computer system",
  "cloud": "Computing services delivered over the internet",
  "server": "Computer or system that provides resources or services to other computers",
  "network": "Connected computers and devices that can communicate with each other",

  // Science
  "photosynthesis": "Process by which plants convert sunlight into chemical energy",
  "ecosystem": "Community of living organisms interacting with their physical environment",
  "coral reef": "Underwater structure made by coral polyps in marine environments",
  "biodiversity": "Variety of plant and animal life in a particular environment",
  "climate change": "Long-term shifts in global temperatures and weather patterns",
  "ocean acidification": "Decrease in ocean pH caused by increased CO2 absorption",
  "marine": "Related to the sea and ocean environments",
  "species": "Group of organisms capable of interbreeding and producing fertile offspring",

  // Business
  "revenue": "Total income generated by a business from selling goods or services",
  "profit": "Financial gain after subtracting expenses from revenue",
  "market": "Arena where goods and services are bought and sold",
  "investment": "Asset or money placed into something with expectation of future returns",
  "stakeholder": "Person or organization with an interest in a business",
  "startup": "Newly established business venture typically based on innovation",

  // General
  "sustainable": "Able to be maintained at a certain level without depleting resources",
  "innovation": "Introduction of new ideas, methods, or technologies",
  "efficiency": "Ability to accomplish a task with minimum wasted effort",
  "analysis": "Detailed examination and study of something",
  "concept": "General idea or understanding of something",
  "strategy": "Plan of action designed to achieve a goal",
  "challenge": "Difficult task or problem requiring effort to overcome",
  "solution": "Answer or method for solving a problem",
}

// Function to extract and highlight glossary terms in text
export function highlightGlossaryTerms(text) {
  let highlightedHTML = text

  // Sort terms by length (longest first) to avoid partial matches
  const sortedTerms = Object.keys(GLOSSARY_TERMS).sort((a, b) => b.length - a.length)

  sortedTerms.forEach((term) => {
    // Create case-insensitive regex that matches whole words only
    const regex = new RegExp(`\\b${term}\\b`, "gi")

    highlightedHTML = highlightedHTML.replace(
      regex,
      `<mark class="glossary-highlight" data-term="${term}" title="Click for definition">${term}</mark>`
    )
  })

  return highlightedHTML
}

// Function to get definition of a term
export function getDefinition(term) {
  const lowerTerm = term.toLowerCase()
  return GLOSSARY_TERMS[lowerTerm] || "Definition not found"
}

// Function to extract all glossary terms found in text
export function extractTermsFromText(text) {
  const plainText = text.replace(/<[^>]*>/g, "").toLowerCase()
  const foundTerms = []

  Object.keys(GLOSSARY_TERMS).forEach((term) => {
    const regex = new RegExp(`\\b${term}\\b`, "gi")
    if (regex.test(plainText)) {
      foundTerms.push(term)
    }
  })

  return [...new Set(foundTerms)] // Remove duplicates
}
